### ISSUE TITLE
duplication on hopper shulker boxes

### ISSUE THREAD

**Issue by ronreydoto** [kyrptonaught/shulkerupgrades#1]
I Encountered a duplication using hopper shulker boxes.

[https://youtu.be/ztC3MPh50z8](url)

**Comment by kyrptonaught** [comment]
Oh wow that's a neat one. Looks like the item isn't getting deleted off the floor once it gets picked up by the shulker. I'll do some investigating

**Comment by kyrptonaught** [comment]
This should be fixed in 1.0.1. Report back if its not
