### ISSUE TITLE
[Request] Update for both 1.18.2 and 1.19 please.

### ISSUE THREAD

**Issue by Terminal-Access** [kyrptonaught/shulkerupgrades#15]
Hey guys love this mod, could we get an update for 1.18.2 as well as 1.19 when you have them time ofc, cheers!

**Comment by kyrptonaught** [comment]
1.1.2 was released for both 1.18.2 and 1.19

**Comment by Terminal-Access** [comment]
> 1.1.2 was released for both 1.18.2 and 1.19

Awesome grabbing this right now thanks! xD
