### ISSUE TITLE
The player inventory is offset one pixel to the left in Diamond and Netherite boxes

### ISSUE THREAD

**Issue by quat1024** [kyrptonaught/shulkerupgrades#19]
Correct appearance:
![image](https://user-images.githubusercontent.com/2068021/191882106-fe8e78b9-a2d9-427b-af7e-2f01ed96671d.png)

Incorrect appearance:
![image](https://user-images.githubusercontent.com/2068021/191882143-972715a5-3d31-43c7-9cc3-613ae3073d40.png)

**Comment by kyrptonaught** [comment]
Fixed in 1.1.3
