### ISSUE TITLE
[feature] Compatibility with curios API

### ISSUE THREAD

**Issue by Panderine** [kyrptonaught/shulkerupgrades#2]
Hi!, I love your mod. Great idea and work !. Would you be so kind as to implement curios API compatibility so that the shulkers can be equipped in the back of the player as an actual backpack?

 Thanks !

**Comment by kyrptonaught** [comment]
Put of curiosity did you check if https://www.curseforge.com/minecraft/mc-mods/curious-shulker-boxes-fabric has any effect?

**Comment by kyrptonaught** [comment]
Looking through the code it doesn't seem like it would have any effect out of the box. But it does have built in support for some other mods adding shulkers. I'd like to see if I could add support for our shulkers there.

**Comment by Panderine** [comment]
yes I tried with that mod, but it only works with vanilla shulkers. It would be PERFECT! if yours could work that way too.
