### ISSUE TITLE
Ignoring NBT Tags

### ISSUE THREAD

**Issue by Dekonker** [kyrptonaught/shulkerupgrades#21]
I made a custom 1.19.2 Fabric modpack with a bunch of mods and noticed certain items were stacking when they have different NBT data. This allows someone to for example fill a tank (MI & IndRev tested) with liquid and then drop an empty tank on the ground and have it become that tank with liquid in it. There were some other examples I noticed from other mod items as well like the Random Rings mod where if you had 2 rings and threw 1 on the ground it would become the ring you still had in your inventory. Once I removed this mod though there was no stacking issue so somehow your mod is causing Minecraft to ignore certain NBT tags allowing for some items to become whatever you're already holding.

Heres my modlist:
  ad-astra-1.0.2-1.19.2.jar
  Adorn-3.6.1+1.19-fabric.jar
  advancednetherite-fabric-1.6.4-1.19.2.jar
  advancementinfo-1.19.1-fabric0.58.5-1.3.1.jar
  AE2WTLib-12.2.0-beta.jar
  Alchemistry-1.19.2-1.0.2.jar
  almostunified-fabric-1.19-0.0.8.jar
  alternate-current-mc1.19-1.4.0.jar
  amecs-1.3.8+mc.1.19-rc2.jar
  amethystequipment-fabric-1.19-v1.0.5.jar
  amethyst_imbuement-1.19-08.jar
  appliedenergistics2-12.5.1-beta.jar
  architectury-6.2.46-fabric.jar
  artifacts-7.1.1+fabric.jar
  AttributeFix-Fabric-1.19.2-17.1.2.jar
  axolotl-item-fix-1.1.3.jar
  badpackets-fabric-0.2.0.jar
  balm-fabric-4.5.2+0.jar
  bclib-2.1.0.jar
  better-end-2.1.0.jar
  better-nether-7.1.0.jar
  bettercombat-fabric-1.4.0+1.19.jar
  BetterF3-1.3.2-Fabric-1.19.jar
  BOMD-1.4.2-1.19.jar
  Bookshelf-Fabric-1.19.2-16.1.5.jar
  borderless-mining-1.1.5+1.19.jar
  BountifulFabric-4.0.0.jar
  bsvsb-3.0.2.jar
  cardinal-components-api-5.0.2.jar
  cc-restitched-1.101.2.jar
  charmofundying-fabric-6.0.0+1.19.2.jar
  ChemLib-1.19.2-1.0.1.jar
  Chunky-1.3.38.jar
  cloth-config-5.3.58-fabric.jar
  cloth-config-8.2.88-fabric.jar
  Clumps-fabric-1.19.2-9.0.0+11.jar
  collective-fabric-1.19.2-4.63.jar
  conjuring-1.0.25+1.19.jar
  consistency_plus-fabric-0.5.1+1.19.2.jar
  Croptopia-1.19.2-FABRIC-2.1.0.jar
  CullLessLeaves-1.0.5.jar
  custom-spawns-0.7+1.19.jar
  DarkPaintings-Fabric-1.19.2-13.1.2.jar
  Debugify-2.6.0.jar
  Decorative Blocks-fabric-1.19.2-3.0.0.jar
  deeperdarker-FABRIC-1.0.2b-1.19.2.jar
  deepmoblearning-refabricated-0.5.7-BETA-build1.jar
  DimensionalDoors-5.0.0-1.19.2.jar
  dragonloot-1.1.2.jar
  DungeonsArise-1.19-2.1.51-fabric-beta-hf.jar
  durabilityviewer-1.19.1-fabric0.58.5-1.10.3.jar
  dynamic-fps-2.2.0.jar
  easiervillagertrading-1.19.1-fabric0.58.5-1.5.4.jar
  eden-ring-0.6.4.jar
  ellemes-container-library-2.0.1+1.19-fabric.jar
  elytraslot-fabric-6.0.0+1.19.2.jar
  EnchantmentDescriptions-Fabric-1.19.2-13.0.3.jar
  end-goblin-traders-1.5.1.jar
  entity-view-distance-1.0.2+1.19.jar
  entityculling-fabric-1.5.2-mc1.19.jar
  EquipmentCompare-1.19-fabric-1.3.1.jar
  exlinecopperequipment-fabric-1.19-v2.1.1.jar
  expandeddelight-0.2.2.jar
  expandedstorage-8.0.1+1.19-fabric.jar
  fabric-api-0.61.0+1.19.2.jar
  fabric-language-kotlin-1.8.3+kotlin.1.7.10.jar
  farmers-delight-fabric-1.19.X-1.3.3.jar
  fixed-villager-trades-1.1.2.jar
  ForgeConfigAPIPort-v4.2.6-1.19.2-Fabric.jar
  frame-0.26.1+1.19-fabric.jar
  ftb-library-fabric-1902.3.9-build.144.jar
  ftb-quests-fabric-1902.4.2-build.116.jar
  ftb-teams-fabric-1902.2.9-build.61.jar
  geckolib-fabric-1.19-3.1.20.jar
  global_packs-fabric-1.19.2-1.14.2_fabric.jar
  goblin-traders-1.5.2.jar
  goodall-1.1.1-fabric.jar
  grind-enchantments-2.0.0-beta.2+1.19.2.jar
  heartytrinkets-1.19-1.0.0.jar
  Highlighter-1.19.1-fabric-1.1.4.jar
  Iceberg-1.19.1-fabric-1.0.46.jar
  indium-1.0.9+mc1.19.2.jar
  indrev-1.15.0-BETA.jar
  indrev-nikolite-1.0+1.19.2.jar
  infusion-table-mod-1.1.0.jar
  IngredientExtensionAPI-fabric-1.19-3.0.3.jar
  inmis-2.7.0-1.19.jar
  InventorySorter-1.8.10-1.19.jar
  iris-mc1.19.2-1.3.1.jar
  item-filters-fabric-1902.2.9-build.41.jar
  item-model-fix-1.0.3+1.19.jar
  jamlib-0.4.4.jar
  Kambrik-4.0-1.19.2.jar
  kofi-table-1.0.4+1.19.x.jar
  kubejs-fabric-1902.6.0-build.66.jar
  lambdynamiclights-2.1.2+1.19.jar
  LibraryFerret-Fabric-1.19-2.0.0.jar
  lithium-fabric-mc1.19.2-0.8.3.jar
  logprot-fabric-1.19.1-1.6.jar
  megane-8.3.0.jar
  memoryleakfix-1.19.1-0.7.0.jar
  midnightlib-0.6.0.jar
  Modern-Industrialization-1.3.2.jar
  modmenu-4.0.6.jar
  moonlight-1.19.2-2.0.28-fabric.jar
  more-geodes-1.5.1.jar
  morediscs-1.19.2-19.jar
  morefrogs-1.19.x-1.2.3-fabric.jar
  moreweaponry-v2.3+1.19.2.jar
  MouseTweaks-fabric-mc1.19-2.22.jar
  naturalist-fabric-2.1.1-1.19.2.jar
  NaturesCompass-1.19.2-2.0.4-fabric.jar
  nbtcrafting-2.2.0+mc1.19.jar
  netherportalfix-fabric-1.19-10.0.0.jar
  notenoughcrashes-4.1.8+1.19.2-fabric.jar
  numeralping-1.0.4.jar
  Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.11.jar
  owo-lib-0.8.2+1.19.jar
  oxidized-1.7.2.jar
  Paintings-fabric-1.19.2-10.2.1.0.jar
  Patchouli-1.19.2-76-FABRIC.jar
  peculiar-pieces-1.2.11+1.19.x.jar
  plasmovoice-fabric-1.19.1-1.2.19.jar
  player-animation-lib-fabric-0.4.0-test1.jar
  polymorph-fabric-0.45.0+1.19.2.jar
  purpeille-3.2.0+fabric-1.19.jar
  PuzzlesLib-v4.3.4-1.19.2-Fabric.jar
  qu-enchantments-1.2.4-1.19.jar
  quartz-elevator-2.1.5+1.19.jar
  RandomRing-Fabric-1.19.2-1.1.26.jar
  realisticsleep-1.5.3.jar
  rebindnarrator-fabric-1.19.x-1.1.jar
  reeses_sodium_options-1.4.7+mc1.19.2-build.59.jar
  repurposed_structures_fabric-6.1.1+1.19.jar
  rer-2.6.0.jar
  revelationary-1.0.2+1.19.2.jar
  rhino-fabric-1802.2.0-build.232.jar
  rightclickharvest-3.0.1.jar
  RingOfProspecting-Fabric-1.19-2.0.2.jar
  RingsOfAscension-1.19.2-1.0.jar
  RoughlyEnoughItems-9.1.537.jar
  RoughlyEnoughLootTables-1.19-1.0.jar
  RoughlyEnoughProfessions-fabric-1.19-1.1.2.jar
  RoughlyEnoughTrades-1.19-1.0.jar
  shulkerboxtooltip-fabric-3.1.3+1.19.2.jar
  silence-1.19.1-fabric0.58.5-1.0.1.jar
  simplechunkloader-1.0.3-1.19.1.jar
  simplyswords-1.23-1.19.jar
  smoothboot-fabric-1.19-1.7.1.jar
  smoothchunk-fabric-1.19.1-2.0.jar
  sodium-extra-0.4.10+mc1.19.2-build.64.jar
  sodium-fabric-mc1.19.2-0.4.4+build.18.jar
  spectrum-1.5.5-1.19.2-magic.jar
  spellbound-1.10.0.jar
  starlight-1.1.1+fabric.ae22326.jar
  stoneholm-1.4.4.jar
  supplementaries-1.19.2-2.2.0-fabric.jar
  TerraBlender-fabric-1.19.2-2.0.1.127.jar
  terraria-trinkets-0.3+1.19.jar
  Thatched-fabric-1.19.2-1.2.0.jar
  the_bumblezone_fabric-6.1.12+1.19.2.jar
  things-0.2.20+1.19.jar
  thonkutil-2.15.4+1.19.jar
  tooltipfix-1.0.5-1.19.jar
  tps-hud-1.5.1+1.19.2.jar
  TradingPost-v4.2.0-1.19.2-Fabric.jar
  transparent-5.1.0+1.19-fabric.jar
  trashcans-0.0.1-1.19.X.jar
  treeharvester-fabric_1.19.2-5.7.jar
  trinkets-3.4.0.jar
  trulytreasures-1.19-2.0.2.jar
  twigs-2.0.0-beta.9+1.19-fabric.jar
  UniversalEnchants-v4.2.7-1.19.2-Fabric.jar
  unstructured-0.5.2+1.19.2.jar
  upgradedechests-1.0.4-1.19.jar
  upgradedshulkers-1.1.2.-1.19.jar
  victus-0.1.12+1.19.jar
  visible-barriers-1.5.3+1.19.x.jar
  voidtotem-fabric-1.19.2-2.1.0.jar
  wanderers-catalogue-1.0.2+1.19.x.jar
  wanderingcollector-1.1.3+mc1.19.jar
  WhatTheBucket-Fabric-1.19.2-7.0.1.jar
  wirelessnetworks-1.6.0.jar
  wthit-fabric-5.12.0.jar
  XaerosWorldMap_1.27.0_Fabric_1.19.1.jar
  Xaeros_Minimap_22.14.1_Fabric_1.19.1.jar
  xpstorage_trinkets-0.1+1.19.jar
  xp_storage-1.4.3+1.19.jar
  YetAnotherConfigLib-1.2.1.jar
  Zoomify-2.6.0.jar

**Comment by quat1024** [comment]
same as #18

**Comment by kyrptonaught** [comment]
Fixed in 1.1.3
