### ISSUE TITLE
[Feature] Increase stackable amount in each tier

### ISSUE THREAD

**Issue by itsdinkd** [kyrptonaught/shulkerupgrades#6]
You have the chance to get a huge audience to download this mod. Dank storages is near unstable and hasn't been updated in 3+ months. Dank storage users are looking for an alternative, and US is it for the pickup/void, but it can also be it even more if you add a feature that allows you to stack items past the 64 amount. Maybe add a 4th version of the box (Base | Void | Pickup | Pickup + Stacks) or just add it in general to all three variations. 

Iron -> 128 stacks per item
Gold -> 256 stacks per item
Diamond > 512 stacks per item
Emerald -> 1024 Stacks per item
etc etc

**Comment by blackd** [comment]
tbh I'm using this mod and not dank storage exactly because it doesn't mess with the stack sizes.

**Comment by kyrptonaught** [comment]
Hmm I'm not exactly a fan on increasing the stack size from 64. Feel as if it's a bit out of scope for this mod, and is quite a big feature to properly implement. I also feel like the 64 stack size is a staple minecraft feature. 

Thank you for the suggestion though! I may revisit this at a later time

**Comment by itsdinkd** [comment]
no problem!
